"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 01:19:40.886539
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("target", sa.String(length=64), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=128), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backups_game"), "backups", ["game"], unique=False)
    op.create_table(
        "hosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hcloud_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROVISIONING",
                "READY",
                "DELETING",
                "DELETED",
                "FAILED",
                name="hoststatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("server_type", sa.String(length=32), nullable=False),
        sa.Column("memory_mb", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("empty_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hcloud_id"),
    )
    op.create_table(
        "game_state",
        sa.Column("game", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "STOPPED",
                "STARTING",
                "RESTORING",
                "RUNNING",
                "STOPPING",
                "BACKING_UP",
                "FAILED",
                name="gamestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_player_count", sa.Integer(), nullable=True),
        sa.Column("last_player_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dirty", sa.Boolean(), nullable=False),
        sa.Column("pinned_backup_id", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pinned_backup_id"],
            ["backups.id"],
        ),
        sa.PrimaryKeyConstraint("game"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_state")
    op.drop_table("hosts")
    op.drop_index(op.f("ix_backups_game"), table_name="backups")
    op.drop_table("backups")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
