"""snapshots

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 02:00:52.518941
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=128), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pulled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game", "filename"),
    )
    op.create_index(op.f("ix_snapshots_game"), "snapshots", ["game"], unique=False)
    op.add_column(
        "game_state", sa.Column("last_snapshot_check_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_state", "last_snapshot_check_at")
    op.drop_index(op.f("ix_snapshots_game"), table_name="snapshots")
    op.drop_table("snapshots")
    # ### end Alembic commands ###
