"""start timing

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 11:29:17.751264
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_state", sa.Column("start_seconds", sa.Integer(), nullable=True))
    op.add_column("game_state", sa.Column("start_new_vm", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_state", "start_new_vm")
    op.drop_column("game_state", "start_seconds")
    # ### end Alembic commands ###
